[32m2021-07-23 12:10:13[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 826c288e-7c7d-4f97-a123-10083b6c46bb - 1038 - format_date - LOGS_CAPTURED - Started capturing logs for solid: format_date.
[32m2021-07-23 12:10:13[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 826c288e-7c7d-4f97-a123-10083b6c46bb - 1038 - format_date - STEP_START - Started execution of step "format_date".
[32m2021-07-23 12:10:14[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 826c288e-7c7d-4f97-a123-10083b6c46bb - 1038 - format_date - LOADED_INPUT - Loaded input "df" using input manager "io_manager", from output "result" of step "extract_dimensions"
[32m2021-07-23 12:10:14[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 826c288e-7c7d-4f97-a123-10083b6c46bb - 1038 - format_date - STEP_INPUT - Got input "df" of type "Any". (Type check passed).
[32m2021-07-23 12:10:14[0m - dagster - [34mERROR[0m - [31mcumulus_pipeline - 826c288e-7c7d-4f97-a123-10083b6c46bb - 1038 - format_date - STEP_FAILURE - Execution of step "format_date" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing solid "format_date"::

AttributeError: 'DataFrame' object has no attribute 'str'

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/utils/__init__.py", line 383, in iterate_with_context
    next_output = next(iterator)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/compute_generator.py", line 65, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/mnt/e/situated-views-etl/solids/cumulus.py", line 156, in format_date
    df.drop(df.str.contains(df["Date"] == "014AM005029"), inplace=True)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
[0m
