[32m2021-06-22 11:16:05[0m - dagster - [34mDEBUG[0m - apis_pipeline - c1052f1e-8e50-4591-955d-997498dc54c4 - 711 - query_portals - LOGS_CAPTURED - Started capturing logs for solid: query_portals.
[32m2021-06-22 11:16:05[0m - dagster - [34mDEBUG[0m - apis_pipeline - c1052f1e-8e50-4591-955d-997498dc54c4 - 711 - query_portals - STEP_START - Started execution of step "query_portals".
[32m2021-06-22 11:16:05[0m - dagster - [34mERROR[0m - [31mapis_pipeline - c1052f1e-8e50-4591-955d-997498dc54c4 - 711 - query_portals - STEP_FAILURE - Execution of step "query_portals" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing solid "query_portals"::

KeyError: 'url'

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/utils/__init__.py", line 382, in iterate_with_context
    next_output = next(iterator)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/definitions/decorators/solid.py", line 307, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/mnt/d/ims/situated-views/bin/solids/apis.py", line 164, in query_portals
    endpoint = context.solid_config["url"]
[0m
