[32m2021-07-01 16:15:27[0m - dagster - [34mDEBUG[0m - apis_pipeline - 533a53b3-c59b-4872-8d8a-4ee36e8ebd99 - 3243 - query_portals - LOGS_CAPTURED - Started capturing logs for solid: query_portals.
[32m2021-07-01 16:15:27[0m - dagster - [34mDEBUG[0m - apis_pipeline - 533a53b3-c59b-4872-8d8a-4ee36e8ebd99 - 3243 - query_portals - STEP_START - Started execution of step "query_portals".
[32m2021-07-01 17:44:29[0m - dagster - [34mERROR[0m - [31mapis_pipeline - 533a53b3-c59b-4872-8d8a-4ee36e8ebd99 - 3243 - query_portals - STEP_FAILURE - Execution of step "query_portals" failed.

dagster.core.errors.DagsterExecutionInterruptedError

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/dagster/core/execution/plan/execute_plan.py", line 193, in _dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/dagster/core/execution/plan/execute_step.py", line 322, in core_dagster_event_sequence_for_step
    _step_output_error_checked_user_event_sequence(step_context, user_event_sequence)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/dagster/core/execution/plan/execute_step.py", line 65, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/dagster/core/execution/plan/compute.py", line 138, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn):
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/dagster/core/execution/plan/compute.py", line 120, in _yield_compute_results
    user_event_generator,
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/dagster/utils/__init__.py", line 382, in iterate_with_context
    next_output = next(iterator)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/dagster/core/execution/plan/compute_generator.py", line 65, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/mnt/e/situated-views/bin/solids/apis.py", line 192, in query_portals
    response = http.post(endpoint, params=params)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-nEZA-I-k/lib/python3.6/site-packages/dagster/utils/interrupts.py", line 78, in _new_signal_handler
    raise error_cls()
[0m
